create footer
IreneTysyachuk/source-code pull request #2
Opened 2023-07-08 13:53 UTC by Olgadz469

2023-07-08 20:34 UTC, IreneTysyachuk requested changes

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/partials/footer.html
> +                <li class="footer-nav-item"><a href="#Contacts"></a>Contacts</li>
Підпис посилань краще добавити в тег посилання, бо при мобайл і таблет вони не відображаються як посилання

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/partials/footer.html
> +            <p class="adress">1678 S. Pioneer Road <br>
краще дати клас footer-adress, як і іншим класам

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/css/footer.css
> +        line-height: 1.33;
text-align має бути start згідно макету

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/css/footer.css
> +    }
text-align має бути start згідно макету (назву класу я прописала в html)

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/css/footer.css
> +}
добавити text-align start телефону та адресі

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/partials/footer.html
> +                  ../img/img_footer/img_veg-min.png 1x,
в посиланні перед слеш має бути одна крапка, щоб відображалось в живій сторінці. Так на всіх.

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/css/footer.css
> +    .footer-nav-item:hover {
тут в одному класі має бути фокус

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/css/footer.css
> +        transition: border 250ms cubic-bezier(0.4, 0, 0.2, 1);
не працює transition на бордер, бонеправильне написання, пишеться в одне правило через кому              
      transition: fill 250ms cubic-bezier(0.4, 0, 0.2, 1),
      border 250ms cubic-bezier(0.4, 0, 0.2, 1);

2023-07-08 20:34 UTC, IreneTysyachuk commented on src/partials/footer.html
> +            </ul>
все лого має бути посиланням, список там не потрібен, список це набір однакових елементів,вони різні. Це просто дів з свг і р в посиланні

2023-07-09 07:22 UTC, Olgadz469 commented on src/partials/footer.html
> +                <li class="footer-nav-item"><a href="#Contacts"></a>Contacts</li>
fixed

2023-07-09 07:22 UTC, Olgadz469 commented on src/partials/footer.html
> +            <p class="adress">1678 S. Pioneer Road <br>
fixed

2023-07-09 07:23 UTC, Olgadz469 commented on src/css/footer.css
> +        line-height: 1.33;
fixed

2023-07-09 07:24 UTC, Olgadz469 commented on src/css/footer.css
> +    }
fixed

2023-07-09 07:25 UTC, Olgadz469 commented on src/css/footer.css
> +}
fixed

2023-07-09 07:26 UTC, Olgadz469 commented on src/partials/footer.html
> +                  ../img/img_footer/img_veg-min.png 1x,
fixed

2023-07-09 07:26 UTC, Olgadz469 commented on src/css/footer.css
> +    .footer-nav-item:hover {
fixed

2023-07-09 07:27 UTC, Olgadz469 commented on src/css/footer.css
> +        transition: border 250ms cubic-bezier(0.4, 0, 0.2, 1);
fixed

2023-07-09 07:33 UTC, Olgadz469 commented on src/partials/footer.html
> +            </ul>
fixed

2023-07-10 23:53 UTC, IreneTysyachuk approved these changes

2023-07-10 23:55 UTC, merged