Serhii vegetables
IreneTysyachuk/source-code pull request #3
Opened 2023-07-08 21:58 UTC by sergeysheva32

2023-07-11 01:31 UTC, IreneTysyachuk requested changes

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +          <use href="/img/icons.svg#icon-arrow"></use>
Kрапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
Одна крапка перед img

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/css/section-2.css
> +  text-shadow: 0px 4px 70px 0px rgba(0, 0, 0, 0.1);
тінь не працює, постав 0px 4px 70px rgba(0, 0, 0, 0.1)

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/css/section-2.css
> +  text-shadow: 0px 4px 70px 0px rgba(0, 0, 0, 0.1);
тінь не працює, постав 0px 4px 70px rgba(0, 0, 0, 0.1)

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/css/section-2.css
> +}
контейнер має бути 
width: 100%;
    max-width: 375px;
    margin: 0 auto; + падінги всі задаєм також контейнеру, а не кожному блоку окремо, узгодь верхній і нижній падінг з тими хто робить сусідні секції

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +  <div class="vegetables-button">
кнопка також має бути в контейнері

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/css/section-2.css
> +    min-width: 768px;
ми задаєм max-width

2023-07-11 01:31 UTC, IreneTysyachuk commented on src/css/section-2.css
> +@media (min-width: 1280px) {
тут також має бути контейнер з max width

2023-07-11 07:17 UTC, sergeysheva32 commented on src/partials/section-2.html
> +                <use href="../img/icons.svg#icon-oval"></use>
готово

2023-07-12 03:49 UTC, IreneTysyachuk requested changes

2023-07-12 03:49 UTC, IreneTysyachuk commented on src/partials/section-2.html
> +            <use href="/img/icons.svg#icon-arrow"></use>
добав крапку перед img

2023-07-12 03:49 UTC, IreneTysyachuk commented on src/css/section-2.css
> +}
варто добавити transition: background-color 250ms cubic-bezier(.4,0,.2,1);

2023-07-12 03:49 UTC, IreneTysyachuk commented on src/css/section-2.css
> +  padding-bottom: 22px;
не padding-bottom: 22px; а margin-bottom: 22px;

2023-07-12 03:49 UTC, IreneTysyachuk commented on src/css/section-2.css
> +
тут є vegetables-card-image, в якому margin-bottom: 32px;

2023-07-12 03:49 UTC, IreneTysyachuk commented on src/css/section-2.css
> +  right: 0;
додати розміри width: 250px;
    height: 94px;

2023-07-12 13:55 UTC, sergeysheva32 commented on src/css/section-2.css
> +
не розумію

2023-07-12 17:16 UTC, IreneTysyachuk approved these changes

2023-07-12 17:16 UTC, merged