Feature/header mob menu
IreneTysyachuk/source-code pull request #5
Opened 2023-07-10 17:00 UTC by artem-yaremchuk

2023-07-11 03:06 UTC, IreneTysyachuk requested changes

2023-07-11 03:06 UTC, IreneTysyachuk commented on src/css/header.css
> +}
не впевнена, що не буде конфлікту

2023-07-11 03:06 UTC, IreneTysyachuk commented on src/index.html
>  </html>
виправлення в основні файли я вношу, пишіть мені, що додати, не лізьте в основні файли, це вже конфлікт і змерджити я це нормально не зможу

2023-07-11 03:06 UTC, IreneTysyachuk commented on src/css/header.css
> +    .container {
назву класу поміняти, вонаповторюється з іншими, всі класи починаєм з header, це по суті header-container, а він може бути header-wrap

2023-07-11 03:06 UTC, IreneTysyachuk commented on src/css/header.css
> +    }
посиланням треба також додати ховер і фокус

2023-07-11 15:02 UTC, artem-yaremchuk commented on src/css/header.css
> +}
я іі пропишу як header-transition, щоб ні у кого не повторювалась.

2023-07-11 15:02 UTC, artem-yaremchuk commented on src/index.html
>  </html>
ми це обговорювали.

2023-07-11 15:02 UTC, artem-yaremchuk commented on src/css/header.css
> +    .container {
виправлено.

2023-07-11 15:02 UTC, artem-yaremchuk commented on src/css/header.css
> +    }
виправлено.

2023-07-12 04:41 UTC, IreneTysyachuk requested changes

2023-07-12 04:41 UTC, IreneTysyachuk commented on src/partials/header.html
> +    <div class="mob-menu js-menu-container is-open">
is-open забираєм, воно додається джеесом привідкритті меню, бо так воно відкрите відразу

2023-07-12 05:38 UTC, artem-yaremchuk commented on src/partials/header.html
> +    <div class="mob-menu js-menu-container is-open">
виправлено.

2023-07-12 13:01 UTC, IreneTysyachuk approved these changes

2023-07-12 13:02 UTC, merged